id: DA1AA247A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-28T09:31:14+00:00'
last_modified: '2022-05-30T07:59:42.292595+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    f46c:
      image_group_id: I1PD96849
      title: འཕགས་པ་ཆོས་བཞི་བསྟན་པ་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོ།
      total_pages: 892
      order: 66
      base_file: f46c.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
