id: PBBE7B05E
initial_creation_type: ocr
source_metadata:
  volumes:
    5009ec67195e4f66abb3cfef069f7515:
      base_file: v066.txt
      image_group_id: I1PD96849
      title: འཕགས་པ་ཆོས་བཞི་བསྟན་པ་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོ།
      total_pages: 892
      volume_number: 66
